rabbitmq_ansible_hostsgroup: rabbitmq-onlyoffice
rabbitmq_master_name: rabbitmq-1
rabbitmq_master_ip: 192.168.40.41
pgsql_ansible_hostsgroup: psql-onlyoffice
pgsql_master_name: pgsqlo1
pgsql_slave_name: pgsqlo2
pgsql_master_ip: 192.168.40.111
pgsql_slave_ip: 192.168.40.112
segment_ip: 192.168.40.0/24
haproxy_back_ansible_hostsgroup: haproxy-back-onlyoffice
redis1_ip: 192.168.40.31
redis2_ip: 192.168.40.32
redis1_port: 6379
redis2_port: 6380
package_oo_name: onlyoffice-documentserver
onlyoffice_default_config: /etc/onlyoffice/documentserver/local.json
rabbitmq_server_user: onlyoffice
rabbitmq_server_pass: onlyoffice
rabbitmq_server_host: 192.168.40.80
rabbitmq_server_vpath: /
json: /var/www/onlyoffice/documentserver/npm/json -q -f {{ onlyoffice_default_config }}
rabbitmq_server_url: "amqp://{{ rabbitmq_server_user }}:{{ rabbitmq_server_pass }}@{{ rabbitmq_server_host }}{{ rabbitmq_server_vpath }}"
onlyoffice_ansible_hostsgroup: onlyoffice